//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userdetail", Namespace="http://schemas.datacontract.org/2004/07/WcfDBService.EF")]
    [System.SerializableAttribute()]
    public partial class userdetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCApp.ServiceReference1.department departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> deptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCApp.ServiceReference1.department department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> deptid {
            get {
                return this.deptidField;
            }
            set {
                if ((this.deptidField.Equals(value) != true)) {
                    this.deptidField = value;
                    this.RaisePropertyChanged("deptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="department", Namespace="http://schemas.datacontract.org/2004/07/WcfDBService.EF")]
    [System.SerializableAttribute()]
    public partial class department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deptCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int deptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCApp.ServiceReference1.employee[] employeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deptCode {
            get {
                return this.deptCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.deptCodeField, value) != true)) {
                    this.deptCodeField = value;
                    this.RaisePropertyChanged("deptCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deptName {
            get {
                return this.deptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.deptNameField, value) != true)) {
                    this.deptNameField = value;
                    this.RaisePropertyChanged("deptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deptid {
            get {
                return this.deptidField;
            }
            set {
                if ((this.deptidField.Equals(value) != true)) {
                    this.deptidField = value;
                    this.RaisePropertyChanged("deptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCApp.ServiceReference1.employee[] employee {
            get {
                return this.employeeField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeField, value) != true)) {
                    this.employeeField = value;
                    this.RaisePropertyChanged("employee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="employee", Namespace="http://schemas.datacontract.org/2004/07/WcfDBService.EF")]
    [System.SerializableAttribute()]
    public partial class employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCApp.ServiceReference1.department departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> deptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string designationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeePhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int employeeidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCApp.ServiceReference1.department department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> deptid {
            get {
                return this.deptidField;
            }
            set {
                if ((this.deptidField.Equals(value) != true)) {
                    this.deptidField = value;
                    this.RaisePropertyChanged("deptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string designation {
            get {
                return this.designationField;
            }
            set {
                if ((object.ReferenceEquals(this.designationField, value) != true)) {
                    this.designationField = value;
                    this.RaisePropertyChanged("designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dob {
            get {
                return this.dobField;
            }
            set {
                if ((this.dobField.Equals(value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employeeAddress {
            get {
                return this.employeeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeAddressField, value) != true)) {
                    this.employeeAddressField = value;
                    this.RaisePropertyChanged("employeeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employeeName {
            get {
                return this.employeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeNameField, value) != true)) {
                    this.employeeNameField = value;
                    this.RaisePropertyChanged("employeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employeePh {
            get {
                return this.employeePhField;
            }
            set {
                if ((object.ReferenceEquals(this.employeePhField, value) != true)) {
                    this.employeePhField = value;
                    this.RaisePropertyChanged("employeePh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeid {
            get {
                return this.employeeidField;
            }
            set {
                if ((this.employeeidField.Equals(value) != true)) {
                    this.employeeidField = value;
                    this.RaisePropertyChanged("employeeid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllUser", ReplyAction="http://tempuri.org/IMyService/GetAllUserResponse")]
        MVCApp.ServiceReference1.userdetail[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllUser", ReplyAction="http://tempuri.org/IMyService/GetAllUserResponse")]
        System.Threading.Tasks.Task<MVCApp.ServiceReference1.userdetail[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddUser", ReplyAction="http://tempuri.org/IMyService/AddUserResponse")]
        int AddUser(string name, string email, int deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddUser", ReplyAction="http://tempuri.org/IMyService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string name, string email, int deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetUserdetailbyId", ReplyAction="http://tempuri.org/IMyService/GetUserdetailbyIdResponse")]
        MVCApp.ServiceReference1.userdetail GetUserdetailbyId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetUserdetailbyId", ReplyAction="http://tempuri.org/IMyService/GetUserdetailbyIdResponse")]
        System.Threading.Tasks.Task<MVCApp.ServiceReference1.userdetail> GetUserdetailbyIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteUserById", ReplyAction="http://tempuri.org/IMyService/DeleteUserByIdResponse")]
        int DeleteUserById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteUserById", ReplyAction="http://tempuri.org/IMyService/DeleteUserByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteUserByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : MVCApp.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<MVCApp.ServiceReference1.IMyService>, MVCApp.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCApp.ServiceReference1.userdetail[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<MVCApp.ServiceReference1.userdetail[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public int AddUser(string name, string email, int deptID) {
            return base.Channel.AddUser(name, email, deptID);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string name, string email, int deptID) {
            return base.Channel.AddUserAsync(name, email, deptID);
        }
        
        public MVCApp.ServiceReference1.userdetail GetUserdetailbyId(int id) {
            return base.Channel.GetUserdetailbyId(id);
        }
        
        public System.Threading.Tasks.Task<MVCApp.ServiceReference1.userdetail> GetUserdetailbyIdAsync(int id) {
            return base.Channel.GetUserdetailbyIdAsync(id);
        }
        
        public int DeleteUserById(int Id) {
            return base.Channel.DeleteUserById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserByIdAsync(int Id) {
            return base.Channel.DeleteUserByIdAsync(Id);
        }
    }
}
